import {
  API_BASE_URL,
  ANDROID_MAP_KEYS,
  IOS_MAP_KEYS,
  PUBLISHABLE_STRIPE_KEY,
  ANDROID_CLIENT_ID,
  IOS_CLIENT_ID,
  WEB_CLIENT_ID,
  OFFLINE_ACCESS,
  APPLE_CLIENT_ID_ANDROID,
  APPLE_REDIRECT_URI,
  APPLE_MERCHANT_ID,
  ANDROID_CHANNEL_ZENDESK,
  MAP_API_KEY,
  IOS_CHANNEL_ZENDESK,
  IS_ALPHA_PHASE,
} from '@env';


export const ENV_CONSTANTS = {
  BASE_URL: API_BASE_URL,
  ANDROID_MAP_KEY: ANDROID_MAP_KEYS,
  IOS_MAP_KEY: IOS_MAP_KEYS,
  STRIPE_KEY: PUBLISHABLE_STRIPE_KEY,
  GOOGLE_ANDROID_CLIENT_ID: ANDROID_CLIENT_ID,
  GOOGLE_WEB_CLIENT_ID: WEB_CLIENT_ID,
  GOOGLE_IOS_CLIENT_ID: IOS_CLIENT_ID,
  GOOGLE_OFFLINE_ACCESS: OFFLINE_ACCESS,
  APPLE_CLIENT_ID_FOR_ANDROID: APPLE_CLIENT_ID_ANDROID,
  APPLE_REDIRECT_URL: APPLE_REDIRECT_URI,
  MERCHANT_ID: APPLE_MERCHANT_ID,
  ZENDESK_ANDROID: ANDROID_CHANNEL_ZENDESK,
  ZENDESK_IOS: IOS_CHANNEL_ZENDESK,
  MAP_API_KEY: MAP_API_KEY,
  IS_ALPHA_PHASE: IS_ALPHA_PHASE === 'true',
};


export const locales = ["en"] as const; // Literal tuple
export type Locale = (typeof locales)[number]; // Creates a union type "en" | "am"

export const VIDEOS = {
  SPLASH_VIDEO: "/assets/common/splash.mp4",
};

export const SUB_TITLE = "/assets/temp/sub.vtt";

export type Locales = (typeof locales)[number];

export const CONSTANTS = {
  LOCALE: "Next-Locale",
  COUNTRY: "US",
  CURRENCY: "UD",
  AREA_UNIT: "Sq.Ft.",
  RETURN_URL: "returnUrl",
  PHONE: "+234 0806 584 1300",
  EMAIL: "email@mail.com",
  ADDRESS: "Address",
  TOKEN: "token",
  USER_ROLE: "user_role",
  USER_STATUS: 0,
  IS_VERIFIED: "is_verified_email",
  NOT_AVAILABLE: "Not Available",
  UDID: "udid",
  APP_STORE_LINK:
    "",
  GOOGLE_STORE_LINK:
    "",
};